%{?!ros_distro:%global ros_distro rolling}
%global pkg_name camera_info_manager_py
%global normalized_pkg_name %{lua:return (string.gsub(rpm.expand('%{pkg_name}'), '_', '-'))}

Name:           ros-rolling-camera-info-manager-py
Version:        6.4.7
Release:        2%{?dist}
Summary:        ROS %{pkg_name} package

License:        BSD-3-Clause
URL:            http://ros.org/wiki/camera_info_manager_py
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  bloom-rpm-macros
BuildRequires:  python%{python3_pkgversion}-devel

%{?bloom_package}

%description
Python interface for camera calibration information. This ROS package provides a
CameraInfo interface for Python camera drivers similar to the C++
camera_info_manager package.


%package devel
Release:        %{release}%{?release_suffix}
Summary:        %{summary}
Provides:       %{name} = %{version}-%{release}
Provides:       %{name}%{?_isa} = %{version}-%{release}
Requires:       %{name}-runtime%{?_isa} = %{version}-%{release}

%description devel
Python interface for camera calibration information. This ROS package provides a
CameraInfo interface for Python camera drivers similar to the C++
camera_info_manager package.


%package runtime
Release:        %{release}
Summary:        %{summary}

%description runtime
Python interface for camera calibration information. This ROS package provides a
CameraInfo interface for Python camera drivers similar to the C++
camera_info_manager package.


%prep
%autosetup -p1


%generate_buildrequires
%bloom_buildrequires


%build
%py3_build


%install
%py3_install -- --prefix "%{bloom_prefix}"


%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "^\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif


%files devel
%dir %{bloom_prefix}
%ghost %{bloom_prefix}/share/%{pkg_name}/package.xml


%files runtime
%{bloom_prefix}


%changelog
* Tue Apr 28 2026 Jose Mastrangelo <jmastrangelo@clearpathrobotics.com> - 6.4.7-2
- Autogenerated by Bloom

* Tue Apr 21 2026 Jose Mastrangelo <jmastrangelo@clearpathrobotics.com> - 6.4.7-1
- Autogenerated by Bloom
